// //////////////Movies//////////////////
export const GET_NETFLIX_ORIGINALS = 'GET_NETFLIX_ORIGINALS'
export const GET_TRENDING_MOVIES = 'GET_TRENDING_MOVIES'
export const GET_TOP_RATED = 'GET_TOP_RATED'
export const GET_ACTIONS_MOVIES = 'GET_ACTIONS_MOVIES'
export const GET_COMEDY_MOVIES = 'GET_COMEDY_MOVIES'
export const GET_HORROR_MOVIES = 'GET_HORROR_MOVIES'
export const SET_MOVIE_DETAIL = 'SET_MOVIE_DETAIL'
export const GET_ROMANCE_MOVIES = 'GET_ROMANCE_MOVIES'
export const GET_SEARCH_MOVIES = 'GET_SEARCH_MOVIES'
export const GET_BACKGROUND = 'GET_BACKGROUND'
export const GET_MOVIE_BY_ID = 'GET_MOVIE_BY_ID'
export const GET_CAST = 'GET_CAST'
export const GET_LIST_MOVIES = 'GET_LIST_MOVIES'
export const GET_TYPE_MOVIES = 'GET_TYPE_MOVIES'
// //////////////////////TV/////////////////////////
export const GET_ON_AIR_TV = 'GET_ON_AIR_TV'
export const GET_TOP_RATE_TV = 'GET_TOP_RATE_TV'
export const GET_TYPES_TV = 'GET_TYPES_TV'
